server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borrow?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111
mybatis-plus:
  mapper-locations: classpath*:com/jxd/borrow/dao/mapping/*.xml
  type-aliases-package: com.jxd.borrow.model